archives:
  - builds:
      - default
    format: binary
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}"

builds:
  - id: "default"
    flags:
      - -trimpath
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"

env:
  - CGO_ENABLED=0
