name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Check out code
        uses: actions/checkout@v2
      - name: Cache Go modules
        uses: actions/cache@v1.1.2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-go-
            ${{ runner.OS }}-
      - name: Get dependencies
        run: go get -v -t -d ./...
      - name: Build
        run: go build -v .
      - name: Test
        run: go test ./...
      - name: Set up golangci-lint
        uses: nickhstr/action-setup-golangci-lint@v0.1.0
        with:
          version: 1.25.0
      - name: Run golangci-lint
        run: |
          bin="$(find /home/runner/work -name golangci-lint)"
          "${bin}" run --enable-all --disable gochecknoglobals,goimports,gomnd,lll,wsl
